"""empty message

Revision ID: 06027adf4a5a
Revises: df9ed70dc0c7
Create Date: 2024-08-01 14:48:45.751629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06027adf4a5a'
down_revision = 'df9ed70dc0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('login_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('max_streak')
        batch_op.drop_column('login_streak')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
