"""empty message

Revision ID: 0c8beac31bea
Revises: 7e89ccaad9d0
Create Date: 2023-11-21 13:53:54.661405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8beac31bea'
down_revision = '7e89ccaad9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('gender')
        batch_op.drop_column('reason')
        batch_op.drop_column('telephone')
        batch_op.drop_column('program')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
