"""empty message

Revision ID: 1944aef937bc
Revises: 0c8beac31bea
Create Date: 2023-11-21 14:02:12.131942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1944aef937bc'
down_revision = '0c8beac31bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('answers', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('program', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reason')
        batch_op.drop_column('telephone')
        batch_op.drop_column('email')
        batch_op.drop_column('program')
        batch_op.drop_column('gender')

    op.drop_table('faq')
    # ### end Alembic commands ###
