"""empty message

Revision ID: 1c2ccde08f66
Revises: 8723426a1489
Create Date: 2024-11-30 14:38:07.168420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2ccde08f66'
down_revision = '8723426a1489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        # Add the 'points' and 'referred_by' columns
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))

        # Create the foreign key constraint with a specified name
        batch_op.create_foreign_key('fk_person_referred_by', 'person', ['referred_by'], ['id'])

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('points')

    # ### end Alembic commands ###
