"""empty message

Revision ID: 1f7dfff3e34f
Revises: 5c19e9320e34
Create Date: 2023-12-03 14:45:31.635287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7dfff3e34f'
down_revision = '5c19e9320e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(), nullable=True),
    sa.Column('studentID', sa.String(), nullable=True),
    sa.Column('studentnumber', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_data')
    # ### end Alembic commands ###
