"""empty message

Revision ID: 34ec36d1684f
Revises: c5c41bf51b8d
Create Date: 2024-04-19 18:29:57.263751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ec36d1684f'
down_revision = 'c5c41bf51b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_code', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('unique_code')

    # ### end Alembic commands ###
