"""empty message

Revision ID: 359aaa01892b
Revises: b96ebadc161b
Create Date: 2024-05-11 09:52:22.818798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359aaa01892b'
down_revision = 'b96ebadc161b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('retail')
        batch_op.drop_column('coorperate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coorperate', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('retail', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
