"""empty message

Revision ID: 36aa3ba57057
Revises: d173cb1ea170
Create Date: 2024-03-11 19:57:28.516424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36aa3ba57057'
down_revision = 'd173cb1ea170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('confirm_password', sa.String(length=128), nullable=True))
        batch_op.drop_column('indexnumber')
        batch_op.drop_column('form')
        batch_op.drop_column('extra')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('extra', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('form', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('indexnumber', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('confirm_password')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
