"""empty message

Revision ID: 399fee634fd1
Revises: dd7db496d1c0
Create Date: 2024-03-30 20:57:40.795437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399fee634fd1'
down_revision = 'dd7db496d1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logger', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
