"""empty message

Revision ID: 3d777c89f7fb
Revises: 7423332ecae8
Create Date: 2024-03-30 18:42:34.160705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d777c89f7fb'
down_revision = '7423332ecae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('activity', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('implementation', sa.String(), nullable=True),
    sa.Column('challenges', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logger')
    # ### end Alembic commands ###
