"""empty message

Revision ID: 411ac8b128ac
Revises: 15ffeb7437b6
Create Date: 2024-03-28 13:03:06.692658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411ac8b128ac'
down_revision = '15ffeb7437b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cisl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('incident', sa.String(), nullable=True),
    sa.Column('casualties', sa.String(), nullable=True),
    sa.Column('employees', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('police', sa.String(), nullable=True),
    sa.Column('fire_force', sa.String(), nullable=True),
    sa.Column('claim', sa.String(), nullable=True),
    sa.Column('name_of_contact', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cisl')
    # ### end Alembic commands ###
