"""empty message

Revision ID: 4786cf649407
Revises: d4fc8992889c
Create Date: 2023-10-15 17:20:35.917368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4786cf649407'
down_revision = 'd4fc8992889c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_filename', sa.String(), nullable=True))
        batch_op.drop_column('pdf_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file', sa.BLOB(), nullable=True))
        batch_op.drop_column('pdf_filename')

    # ### end Alembic commands ###
