"""empty message

Revision ID: 4bab5bffb037
Revises: 399fee634fd1
Create Date: 2024-04-12 17:09:33.799720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bab5bffb037'
down_revision = '399fee634fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('tag',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
