"""empty message

Revision ID: 5c19e9320e34
Revises: c256032f5b65
Create Date: 2023-12-03 13:35:11.164295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c19e9320e34'
down_revision = 'c256032f5b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studenthalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(), nullable=True),
    sa.Column('regno', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hallname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studenthalls')
    # ### end Alembic commands ###
