"""empty message

Revision ID: 5c6f1697d114
Revises: 06027adf4a5a
Create Date: 2024-08-14 13:59:37.521028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6f1697d114'
down_revision = '06027adf4a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messageId', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_streak')
        batch_op.drop_column('last_login')
        batch_op.drop_column('max_streak')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_streak', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('login_streak', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('messageId')

    # ### end Alembic commands ###
