"""empty message

Revision ID: 7188f06c04e5
Revises: 566b32aab115
Create Date: 2023-09-19 11:47:22.208148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7188f06c04e5'
down_revision = '566b32aab115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yearCompleted', sa.Integer(), nullable=True))
        batch_op.drop_column('admitted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admitted', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('yearCompleted')

    # ### end Alembic commands ###
