"""empty message

Revision ID: 7ff226557380
Revises: 62a96666da93
Create Date: 2023-08-22 07:29:04.337976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff226557380'
down_revision = '62a96666da93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('directress', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('others', sa.String(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('others')
        batch_op.drop_column('directress')
        batch_op.drop_column('director')

    # ### end Alembic commands ###
