"""empty message

Revision ID: 848cd5f2c845
Revises: 8dca0380e19c
Create Date: 2024-02-11 12:34:30.600578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848cd5f2c845'
down_revision = '8dca0380e19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=255), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
