"""empty message

Revision ID: 89418ec29ddd
Revises: 4786cf649407
Create Date: 2023-10-17 19:59:52.240888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89418ec29ddd'
down_revision = '4786cf649407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ask', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ask')
    # ### end Alembic commands ###
