"""empty message

Revision ID: 90996403507e
Revises: 006ae51fe6e2
Create Date: 2024-04-19 18:05:10.886996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90996403507e'
down_revision = '006ae51fe6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faqid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_column('faqid')

    # ### end Alembic commands ###
