"""empty message

Revision ID: a4d94463e2ff
Revises: e296f05700cd
Create Date: 2024-03-17 16:26:38.389073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d94463e2ff'
down_revision = 'e296f05700cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('committee', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
