"""empty message

Revision ID: a6804d733eee
Revises: d79f0bc87a6b
Create Date: 2023-08-29 09:26:44.511257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6804d733eee'
down_revision = 'd79f0bc87a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaders')
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('directress', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('others', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ministries', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('total_number')
        batch_op.drop_column('ministries')
        batch_op.drop_column('others')
        batch_op.drop_column('directress')
        batch_op.drop_column('director')

    op.create_table('leaders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ministries', sa.VARCHAR(), nullable=True),
    sa.Column('total_number', sa.VARCHAR(), nullable=True),
    sa.Column('director', sa.VARCHAR(), nullable=True),
    sa.Column('directress', sa.VARCHAR(), nullable=True),
    sa.Column('others', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
