"""empty message

Revision ID: ab061913f613
Revises: 359aaa01892b
Create Date: 2024-06-05 09:52:18.808918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab061913f613'
down_revision = '359aaa01892b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('company_email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('company_email', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
