"""empty message

Revision ID: b070a095d108
Revises: 5c6f1697d114
Create Date: 2024-08-14 16:57:56.207599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b070a095d108'
down_revision = '5c6f1697d114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messageid', sa.Integer(), nullable=True))
        batch_op.drop_column('messageId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messageId', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('messageid')

    # ### end Alembic commands ###
