"""empty message

Revision ID: c5c41bf51b8d
Revises: 90996403507e
Create Date: 2024-04-19 18:10:45.156731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c41bf51b8d'
down_revision = '90996403507e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budgetId', sa.Integer(), nullable=True))

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taskId', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('taskId')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_column('budgetId')

    # ### end Alembic commands ###
