"""empty message

Revision ID: d309e8dd7d00
Revises: 063ab3d2ecf7
Create Date: 2024-11-30 14:26:46.400947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd309e8dd7d00'
down_revision = '063ab3d2ecf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint('unique_email_constraint', ['email'])
        batch_op.create_unique_constraint(None, ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('unique_email_constraint', type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('points')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referral_code')

    # ### end Alembic commands ###
