"""empty message

Revision ID: dd7db496d1c0
Revises: 3d777c89f7fb
Create Date: 2024-03-30 20:18:30.666518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7db496d1c0'
down_revision = '3d777c89f7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('future', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logger', schema=None) as batch_op:
        batch_op.drop_column('future')

    # ### end Alembic commands ###
