"""empty message

Revision ID: e0e62baed5ea
Revises: 1f7dfff3e34f
Create Date: 2024-01-05 18:18:17.757004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e62baed5ea'
down_revision = '1f7dfff3e34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ministry')
        batch_op.drop_column('email')
        batch_op.drop_column('program')
        batch_op.drop_column('telephone')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('program', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ministry', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
