"""empty message

Revision ID: e275524cbc81
Revises: 3e5f2c5ca002
Create Date: 2023-10-13 15:18:12.900443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e275524cbc81'
down_revision = '3e5f2c5ca002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_file', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
