"""empty message

Revision ID: e55ca95f326d
Revises: e662d90ef05a
Create Date: 2024-03-20 11:41:18.058002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55ca95f326d'
down_revision = 'e662d90ef05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tag', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('tag')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
