"""empty message

Revision ID: e662d90ef05a
Revises: db06d5b3fe4e
Create Date: 2024-03-20 09:18:37.169861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e662d90ef05a'
down_revision = 'db06d5b3fe4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('date_completed', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    # ### end Alembic commands ###
