"""empty message

Revision ID: eea64b007938
Revises: b8a7aaf2a29a
Create Date: 2023-08-21 17:03:56.839544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea64b007938'
down_revision = 'b8a7aaf2a29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hall')
        batch_op.drop_column('extra')
        batch_op.drop_column('work')
        batch_op.drop_column('marital')
        batch_op.drop_column('kin')
        batch_op.drop_column('guardian')
        batch_op.drop_column('address')
        batch_op.drop_column('department')
        batch_op.drop_column('health')
        batch_op.drop_column('admitted')
        batch_op.drop_column('school')
        batch_op.drop_column('nationality')
        batch_op.drop_column('relationship')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('relationship', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('school', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('admitted', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('health', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('guardian', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('kin', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('marital', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('work', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('extra', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('hall', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
