"""empty message

Revision ID: f112be70b606
Revises: a49578bcea0d
Create Date: 2024-11-17 07:14:58.518787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f112be70b606'
down_revision = 'a49578bcea0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bus_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('currency')
        batch_op.drop_column('bus_email')

    # ### end Alembic commands ###
