name: Deploy Alumni App

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with the path to your requirements file

      - name: Deploy with uWSGI
        run: |
          # Install uWSGI and any other necessary dependencies
          sudo apt-get update
          sudo apt-get install -y uwsgi

          # Create a uWSGI configuration file
          echo "[uwsgi]
                module = wsgi:application
                master = true
                processes = 4 # Adjust as needed
                socket = :3031  # Adjust the port
                chmod-socket = 660
                vacuum = true
                die-on-term = true" > uwsgi.ini

          # Start the uWSGI server
          uwsgi uwsgi.ini

      - name: Check service status
        run: sudo systemctl status uwsgi.service

      - name: Set up SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh-keyscan -t rsa 45.222.128.55 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Debug
        run: |
          echo "SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}"

      - name: Deploy to CentOS Server
        run: |
          scp -i deploy_key.pem -r ./* kweku@45.222.128.55:/home/kweku/hello

      - name: Restart uWSGI on CentOS Server
        run: ssh kweku@45.222.128.55 'sudo systemctl restart uwsgi.service'
